services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .data:/var/lib/postgresql/data
    restart: unless-stopped
  web-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/postgres"
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      - timescaledb
    restart: unless-stopped