services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    user: "0:0"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/home/postgres/pgdata/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  # web-app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/postgres
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/src
  #   depends_on:
  #     - timescaledb
  #   restart: unless-stopped

#volumes:
#  postgres_data:

# restore db from dump
# gunzip -c ./data_backups/backup-2025-02-28T00-35-06-379Z.sql.gz | docker exec -i timescaledb psql -U postgres